### ISSUE TITLE
GNOME Shell Crashes On Notification Arrival

### ISSUE THREAD

**Issue by ghost** [ZorinOS/gnome-shell-extension-zorin-connect#1]
Notifications arriving through Zorin Connect seem to crash the shell about 10 times per day. I'd love to be able to use this feature, but I always end up disabling it after a day because it becomes too annoying. I've finally been able to capture on of these events in a support log.

Any ideas what could be causing this? I'd love to be able to get it working properly.

[zorin-connect.txt](https://github.com/ZorinOS/gnome-shell-extension-zorin-connect/files/4454821/zorin-connect.txt)

**Comment by ArtyomZorin** [comment]
Thanks for reporting this issue! Have you tested whether this issue still occurs after disabling all third-party Gnome Shell extensions (all of the non-"Zorin" extensions, with the exception of "Removable drive menu" and "User themes") from Gnome Tweaks?

Often times, crashes may occur when there is an unexpected conflict between different extensions which may not play well together.

**Comment by ghost** [comment]
Thanks for the response!

The only Gnome Shell extension I use is 'unblank'. It's the same without that installed. The same thing happens with a brand new install before I've even touched it. I've been testing Zorin Connect for months because I'd really love to use it, but that constant shell crashes make it unusable for me.

It seems to be something to do with the notification popup. After Gnome Shell has restarted, the notification that caused the crash is in the notification panel. I just never see the popup. Also, this seems to be present in all the logs I've looked at.

Apr 09 08:56:25 gnome-shell[4225]: JS WARNING: [resource:///org/gnome/shell/ui/popupMenu.js 727]: reference to undefined property "_delegate"
