### ISSUE TITLE
Remote F-Droid installs?

### ISSUE THREAD

**Issue by nicolasmaia** [ZorinOS/gnome-shell-extension-zorin-connect#2]
It would be very cool if, when looking at pages like

* https://f-droid.org/packages/org.mozc.android.inputmethod.japanese/
or
* https://fossdroid.com/a/mozc-for-android.html

Zorin Connect would somehow tell the F-Droid on Android to download the app (opening the apk link on mobile). Maybe by prompting the user or via a usercript, adding an extra button in those pages.

This is already possible simply by sending the apk link to mobile, but it'd be nice to have a more elegant, automatic solution.

This might be more useful to be applied to the webextension.

**Comment by ArtyomZorin** [comment]
Thank you for your suggestion! however, we won't be including this functionality as it's a little out-of-scope from how Zorin Connect is intended to work. In addition, this would require us to add code to read the user's webpage content, which we're reluctant to add for privacy reasons.
