### ISSUE TITLE
Sharing Web Page From PC to Mobile Device Not Working

### ISSUE THREAD

**Issue by JDMorris81** [ZorinOS/gnome-shell-extension-zorin-connect#8]
Sharing web page from mobile device to pc works fine but not the reverse.

**Comment by marenostrum1981** [comment]
Not working for me.
Chrome or Edge.

It show in console: Unchecked runtime.lastError: Native host has exited

**Comment by rodrigoswz** [comment]
Any update of this issue? Firefox extensions doesn't work here. 

![image](https://github.com/ZorinOS/gnome-shell-extension-zorin-connect/assets/14058427/6d57ba1d-a327-4f18-8276-c1c5a0613849)

**Comment by ArtyomZorin** [comment]
We previously shipped the Flatpak version of Firefox, which isn't currently able to work with the [gnome-browser-connector](https://wiki.gnome.org/Projects/GnomeShellIntegration/Installation) that Zorin Connect uses to integrated with the browser. This appears to be the same with other browsers that were installed as Flatpak packages.

As of 15 June, we've switched to shipping the APT version of Firefox with the [Zorin OS 17.1 r2](https://forum.zorin.com/t/zorin-os-17-1-r2/38399) revised release. This version of Firefox works with the gnome-browser-connector and can therefore integrate with Zorin Connect, solving this issue.

Please note that existing Zorin OS 17 users who have the Flatpak version of Firefox installed will not be automatically migrated to the APT version. If you wish to install the APT version, you will need to follow the instructions on Mozilla's website: https://support.mozilla.org/en-US/kb/install-firefox-linux#w_install-firefox-deb-package-for-debian-based-distributions
Afterwards, you can remove the Firefox Flatpak package by opening the Terminal (Ctrl+Alt+T) and entering this command: `flatpak uninstall org.mozilla.firefox`
Please note that this will clear your previous browser data, history, and bookmarks.
