### ISSUE TITLE
There is no way to delete a Phone?

### ISSUE THREAD

**Issue by grafst** [ZorinOS/gnome-shell-extension-zorin-connect#9]
I am amazed by Zorin-Connect. However I was unable to find a way to un-pair my phone?

**Comment by ArtyomZorin** [comment]
You can unpair a device by opening the Zorin Connect app on your computer or phone, selecting your device, clicking the 3-dot button in the top-right corner and selecting "Unpair" from the menu.

For further technical support requests, please use our forum: https://forum.zorin.com/
